name: Notebook
services:

  postgres:
    image: postgres:16.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  express-api:
    build:
      context: .
    container_name: express_api
    restart: always
    ports:
      - "${EXPRESS_API_PORT}:${EXPRESS_API_PORT}"
      - "${PRISMA_PORT}:${PRISMA_PORT}"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public"
    volumes:
      - ./express-api:/app
      - node_modules:/app/node_modules