name: Notebook
services:
  postgres:
    image: postgres:16.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  express-api:
    build:
      context: ./Backend
    container_name: express_api
    restart: always

    ports:
      - "${EXPRESS_API_PORT}:${EXPRESS_API_PORT}"
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL_PRODUCTION}
      EXPRESS_API_PORT: ${EXPRESS_API_PORT}
      CLIENT_SIDE_PORT: ${CLIENT_SIDE_PORT}

    volumes:
      - /app/node_modules

  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_EXPRESS_API_PORT=${VITE_EXPRESS_API_PORT}
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules

volumes:
  postgres_data: